services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - mynetwork
  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    networks:
      - mynetwork

volumes:
  mongodb_data:


networks:
  mynetwork:
    driver: bridge
